# Example:
# --config benchmarks.yml --scenario proxy-yarp --profile aspnet-physical

imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BenchmarksDriver2/benchmarks.proxy.yml

jobs:
  yarp:
    source:
      repository: https://github.com/microsoft/reverse-proxy.git
      branchOrCommit: master
      project: samples/BenchmarkApp/BenchmarkApp.csproj
    readyStateText: Application started.
    arguments: '--urls {{serverScheme}}://*:5000 --clusterUrls {{downstreamScheme}}://{{downstreamAddress}}:{{downstreamPort}}'
    port: 5000

scenarios:
  proxy-yarp:
    downstream:
      job: downstream
    application:
      job: yarp
    load:
      job: bombardier
  proxy-yarp-http2:
    downstream:
      job: downstream
      variables:
        httpProtocol: Http2
    application:
      job: yarp
    load:
      job: bombardier 
      variables:
        transport: http2
